CREATE TABLE Users (
	uid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL,
	password CHAR(60) NOT NULL,
	
	PRIMARY KEY(uid),
	UNIQUE(email)
);

CREATE TABLE History (
	hid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	uid SMALLINT UNSIGNED NOT NULL,
	completion_date DATETIME NOT NULL,
	workout_name TEXT NOT NULL,

	PRIMARY KEY(hid),
	FOREIGN KEY (uid)
		REFERENCES Users(uid)
);

CREATE TABLE ExerciseHistory (
	ehid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	hid SMALLINT UNSIGNED NOT NULL,
	name TEXT NOT NULL,
	sets TINYINT UNSIGNED NOT NULL,
	reps TINYINT UNSIGNED NOT NULL,
	weight SMALLINT UNSIGNED NOT NULL,

	PRIMARY KEY(ehid),
	FOREIGN KEY(hid)
		REFERENCES History(hid)
);

CREATE TABLE Workouts (
	wid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	uid SMALLINT UNSIGNED,
	name TEXT NOT NULL,
	days SET('M', 'TU', 'W', 'TH', 'F', 'SA', 'SU'),
		
	PRIMARY KEY(wid),
	FOREIGN KEY(uid)
		REFERENCES Users(uid)
);

CREATE TABLE Exercises (
	eid SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	wid SMALLINT UNSIGNED,
	name TEXT NOT NULL,
	sets TINYINT UNSIGNED NOT NULL,
	reps TINYINT UNSIGNED NOT NULL,
	weight SMALLINT UNSIGNED NOT NULL,
	
	PRIMARY KEY(eid),
	FOREIGN KEY(wid)
		REFERENCES Workouts(wid)
);
